<a href="https://colab.research.google.com/github/theunixdisaster/Reinforcement_Learning_NPTEL/blob/main/pytorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import torch
import numpy as np

tensor = torch.rand(3, 3)
ones = torch.ones(3, 3)

if torch.cuda.is_available():
  tensor = tensor.to("cuda")
  ones = ones.to("cuda")

tensor @ tensor.T

tensor([[0.9610, 0.5615, 0.5679],
        [0.5615, 0.4400, 0.6550],
        [0.5679, 0.6550, 1.2694]], device='cuda:0')

In [11]:
torch.matmul(tensor, tensor.T, out=ones)

tensor([[0.9610, 0.5615, 0.5679],
        [0.5615, 0.4400, 0.6550],
        [0.5679, 0.6550, 1.2694]], device='cuda:0')

In [12]:
ones

tensor([[0.9610, 0.5615, 0.5679],
        [0.5615, 0.4400, 0.6550],
        [0.5679, 0.6550, 1.2694]], device='cuda:0')

This means that the out parameter of matmul stores the output tensor the tensor passed on to it